# Giovanni's paths
data_dir: /Users/giovanni/Desktop/Tesi di Laurea/database
bounding_boxes_dir: /Users/giovanni/Desktop/Tesi di Laurea/yolo_annotations
model_weights_path: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/ear_dx_yolo_detection/pre_trained_model
save_data_splitted_path: /Users/giovanni/Desktop/Tesi di Laurea
save_path: /Users/giovanni/Desktop/Tesi di Laurea/images


comet:
  api_key: f0ogWRIW8kCHAzBzpvnkh1kbn
  project_name: ear_dx-detection
  workspace: Joyde-1

browse_path: False

save_image:
  plot_prediction: True

show_image:
  plot_prediction: False

train_yolo_model_path: yolo_detection/config/ear_dx_train_yolo_model.yaml

data:
  image_size: 128
  val_size: 0.25
  test_size: 0.2

training:
  model_name: yolo11n
  epochs: 100
  batch_size: 8
  device: cpu #mps
  checkpoints_dir: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/ear_dx_yolo_detection
  min_delta: 0
  patience: 90
  start_from_epoch: 16