# Alfredo's paths
data_dir: /Users/alfredovecchio/Desktop/Magistrale/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/face_autentication_project/project_database/database
bounding_boxes_dir: /Users/alfredovecchio/Desktop/Magistrale/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/face_autentication_project/project_database/annotations
model_weights_path: /Users/alfredovecchio/Desktop/Magistrale/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/face_autentication_project/project_database/model_checkpoints/face_detection/pre_trained_model
save_data_splitted_path: /Users/alfredovecchio/Desktop/Magistrale/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/face_autentication_project
save_path: /Users/alfredovecchio/Desktop/Magistrale/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/face_autentication_project/splitted database/images

# Giovanni's paths
data_dir: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/database
bounding_boxes_dir: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/annotations
model_weights_path: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/model_checkpoints/face_detection/pre_trained_model
save_data_splitted_path: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto
save_path: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/images


comet:
  #api_key: zsLnCzFjSbQ2wuLTcFpHzVhQY
  api_key: f0ogWRIW8kCHAzBzpvnkh1kbn
  project_name: face-detection
  #workspace: alfrix1
  workspace: Joyde-1

browse_path: False

save_image:
  plot_prediction: True

show_image:
  plot_prediction: False

train_yolo_model_path: face/face_detection_yolo/config/train_yolo_model.yaml

data:
  image_size: 128
  val_size: 0.25
  test_size: 0.2

training:
  model_name: yolo11n
  epochs: 100
  batch_size: 8
  device: cpu #mps
  # checkpoints_dir: /Users/alfredovecchio/Desktop/Magistrale/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/face_autentication_project/project_database/model_checkpoints/face_detection
  checkpoints_dir: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/model_checkpoints/face_detection
  min_delta: 0
  patience: 9
  start_from_epoch: 16

optimizer: 
  adam:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0

scheduler:
  reduce_lr_on_plateau:
    factor: 0.1 
    patience: 7
    threshold: 0.001 
    threshold_mode: rel
    cooldown: 1
    min_lr: 0.00001 
    eps: 1e-08
  cosine_annealing_warm_restarts:
    t_0: 7
    t_mult: 2
    eta_min: 0.00001
    last_epoch: -1
  warm_up:
    warmup_ratio: 0.1