# Data paths
# path: /Users/alfredovecchio/Desktop/Magistrale/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/face_autentication_project/splitted database/face
path: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/splitted database/face

train: train
val: val
test: test

# train:
#   images: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/splitted database/face/train/images
#   labels: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/splitted database/face/train/bounding_boxes

# val:
#   images: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/splitted database/face/val/images
#   labels: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/splitted database/face/val/bounding_boxes

# test:
#   images: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/splitted database/face/test/images
#   labels: /Users/giovanni/Desktop/Autenticazione Biometrica per la Sicurezza dei Sistemi Informatici/Progetto/splitted database/face/test/bounding_boxes

# Number of classes
nc: 1

# Classes names
# names: ['face']
names: 
  0: 'face'