frames_dir: /Users/giovanni/Desktop/Tesi di Laurea/OU-MVLP/silhouette
keypoints_sequences_dir: /Users/giovanni/Desktop/Tesi di Laurea/gait_detected_keypoints_sequences
# keypoints_sequences_dir: /Users/giovanni/Desktop/Tesi di Laurea/OUMVLP-Pose/pose_sequences/openpose
model_weights_path: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait_keypoints_detection/pre_trained_model
save_data_splitted_path: /Users/giovanni/Desktop/Tesi di Laurea
save_path: /Users/giovanni/Desktop/Tesi di Laurea/images

comet:
  api_key: f0ogWRIW8kCHAzBzpvnkh1kbn
  project_name: gait_embedding_extraction
  workspace: Joyde-1

browse_path: False

show_image:
  plot_data_splitting: False
  plot_tsne: False
  plot_prediction: False
  plot_reference_vs_prediction: False

save_image:
  save_loaded_image: True
  plot_data_splitting: True
  plot_tsne: True
  plot_prediction: True
  plot_reference_vs_prediction: True

data:
  num_classes: 49
  selected_angles: [30, 60, 90] # [0, 15, 30, 45, 60, 75, 90]  # CAMBIATO: più angoli per più dati
  image_width: 1280
  image_height: 960
  image_size: 128
  val_size: 0.2  # CAMBIATO da 0.25 a 0.2
  # test_size: 0.2
  data_augmentation: True
  data_augmentation_params:
    sigma: 0.005
    min_scale: 0.9
    max_scale: 1.1
    shift_max: 2
    # val_augmentation: False
    # test_augmentation: False
    # num_augmentation_operations: 4  # CAMBIATO da 6 a 4
    # angle_deg_min: -5  # CAMBIATO da -10 a -5
    # angle_deg_max: 5   # CAMBIATO da 10 a 5
    # scale_factor_min: 0.95  # CAMBIATO da 0.9 a 0.95
    # scale_factor_max: 1.05  # CAMBIATO da 1.1 a 1.05
    # shift_x_min: -3  # CAMBIATO da -5 a -3
    # shift_x_max: 3   # CAMBIATO da 5 a 3
    # shift_y_min: -3  # CAMBIATO da -5 a -3
    # shift_y_max: 3   # CAMBIATO da 5 a 3
    # sigma: 1.0       # CAMBIATO da 1.5 a 1.0
    # drop_prob: 0.1   # CAMBIATO da 0.2 a 0.1
  # interpolation_method: linear
  # normalization_method: hip_center
  fixed_length: 32
  flatten: True
  # add_frame_method: reply # reply
  # delete_frame_method: truncate # downsample
  # scaler: None
  # scaler_dir: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait_embedding_extraction

training:
  model_name: gait_model
  epochs: 120  # CAMBIATO da 100 a 50 per test iniziali
  batch_size: 32  # CAMBIATO da 16 a 32
  scheduler_name: cosine
  device: mps
  checkpoints_dir: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait_embedding_extraction
  evaluation_metric: EER
  min_delta: 0.00001  # CAMBIATO da 0 a 0.001
  patience: 15       # CAMBIATO da 9 a 7
  lower_is_better: True
  initial_value_threshold: None
  save_best_weights: True
  start_from_epoch: 15  # CAMBIATO da 16 a 0 per ricominciare
  num_workers: 4       # CAMBIATO da 8 a 4

# loss_function:
#   arcface:
#     margin: 0.3  # CAMBIATO da 0.5 a 0.3
#     scale: 20.0  # CAMBIATO da 30.0 a 20.0
#   triplet:
#     margin: 0.5  # CAMBIATO da 1.0 a 0.5
#     alpha: 0.7   # CAMBIATO da 0.3 a 0.7
#   center:
#     beta: 0.1    # AGGIUNTO per center loss

optimizer: 
  adamw:
    lr: 0.0003      # CAMBIATO da 0.001 a 0.0005
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0.0001  # CAMBIATO da 0.0001 a 0.01

scheduler:
  reduce_lr_on_plateau:
    factor: 0.7     # CAMBIATO da 0.5 a 0.7
    patience: 5     # CAMBIATO da 10 a 5
    threshold: 0.01 # CAMBIATO da 0.001 a 0.01
    threshold_mode: rel
    cooldown: 2     # CAMBIATO da 1 a 2
    min_lr: 0.00001
    eps: 1e-08
  cosine_annealing_warm_restarts:
    t_0: 7
    t_mult: 2
    eta_min: 0.00001
    last_epoch: -1
  warm_up:
    warmup_ratio: 0.1ù
  cosine:
    warmup_epochs: 10

model:
  backbone:
    num_joints: 12         # joints after filtering (no eyes/ears)
    embed_dim: 256         # 256 (Small) or 128 (Tiny if tiny=true)
    num_heads: 4            # 4 (Small) or 2 (Tiny if tiny=true)
    tiny: False            # true → embed_dim 128, heads 2
  head:
    scale: 30.0          # ArcFace scale s
    margin: 0.50         # ArcFace margin m (radians)
    lambda_center: 0.10  # weight for CenterLoss


  # input_dim: 51
  # hidden_dim: 256
  # lstm_layers: 2
  # embedding_dim: 64  # CAMBIATO da 128 a 256
  # dropout: 0.2        # CAMBIATO da 0.3 a 0.2