data_dir: /Users/giovanni/Desktop/Tesi di Laurea/OU-MVLP/silhouette
keypoints_sequences_dir: /Users/giovanni/Desktop/Tesi di Laurea/OUMVLP-Pose/pose_sequences/openpose
save_path: /Users/giovanni/Desktop/Tesi di Laurea
save_detected_keypoints_sequences_path: /Users/giovanni/Desktop/Tesi di Laurea/gait_detected_keypoints_sequences
results_path: /Users/giovanni/Desktop/Tesi di Laurea/results
models_dir: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait

browse_path: False
use_checkpoint: False
save_detected_keypoints: False # True

matching_algorithm: cosine_distance

# On/Off show images
show_images:
  pre_processed: False
  detected_keypoints: False
  visualize_keypoints: False  # Visualize keypoints on the original frame

save_image:
  pre_processed: False
  detected_keypoints: False
  post_processed: False

data:
  num_classes: 40
  sequence_names: ['060-01', '075-00', '075-01', '090-00', '090-01']
pre_processing:
  frame_width: 128
  frame_height: 128
  padding: 20
  interpolation_method: linear
  normalization_method: hip_center
  add_frame_method: reply # reply
  delete_frame_method: truncate
  fixed_length: 25 # 32 # 25
  scaler: standard # None # standard
detection:
  image_size: 128 

matching:
  test_ratio: 0.2 # 0.2
  threshold: 0.5