data_dir: /Users/giovanni/Desktop/Tesi di Laurea/OU-MVLP/silhouette/Silhouette_000-90/00001
keypoints_dir: /Users/giovanni/Desktop/Tesi di Laurea/OU-MVLP-Pose/silhouette/Silhouette_000-00/00001
save_dir: /Users/giovanni/Desktop/Tesi di Laurea/extracted_keypoits
results_path: /Users/giovanni/Desktop/Tesi di Laurea/results
predictor_path: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/face_detection
models_dir: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait

browse_path: False