# Paths
data_dir: /Users/giovanni/Desktop/Tesi di Laurea/database
save_path: /Users/giovanni/Desktop/Tesi di Laurea
results_path: /Users/giovanni/Desktop/Tesi di Laurea/results

browse_path: False

show_image:
  plot_pca_cumulative_variance: True

save_images:
  pre_processed: True
  detected: True
  post_processed: True
  features_extracted: True
  pca_cumulative_variance: True

matching_algorithm: euclidean # euclidean # chi-square #hamming

features_fusion:
  scaler_type: 'standard'
  # Definisce i pesi per ciascuna modalità
  weight_gait: 0.3
  weight_face: 0.4
  weight_ear: 0.15 

matching:
  threshold: 0.4

score_fusion:
  weight_gait: 0.3
  weight_face: 0.4
  weight_ear: 0.15 
  threshold: 0.37