frames_dir: /Users/giovanni/Desktop/Tesi di Laurea/OU-MVLP/silhouette
keypoints_dir: /Users/giovanni/Desktop/Tesi di Laurea/OUMVLP-Pose/pose_sequences/openpose
model_weights_path: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait_keypoints_detection/pre_trained_model
save_data_splitted_path: /Users/giovanni/Desktop/Tesi di Laurea
save_path: /Users/giovanni/Desktop/Tesi di Laurea/images

comet:
  api_key: f0ogWRIW8kCHAzBzpvnkh1kbn
  project_name: gait_keypoints_detection
  workspace: Joyde-1

browse_path: False

save_image:
  plot_prediction: True

show_image:
  plot_prediction: False

train_gait_keypoints_detection_model_path: yolo_detection/config/train_gait_keypoints_detection_model.yaml

data:
  image_width: 256
  image_height: 192
  val_size: 0.25
  test_size: 0.2

training:
  model_name: yolo11n
  epochs: 100
  batch_size: 8
  device: mps #mps
  checkpoints_dir: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait_keypoints_detection
  min_delta: 0
  patience: 90
  start_from_epoch: 16