# Giovanni's paths
frames_dir: /Users/giovanni/Desktop/Tesi di Laurea/OU-MVLP/silhouette
keypoints_dir: /Users/giovanni/Desktop/Tesi di Laurea/OUMVLP-Pose/pose_sequences/openpose
model_weights_path: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait_yolo_pose_detection/pre_trained_model
save_data_splitted_path: /Users/giovanni/Desktop/Tesi di Laurea
save_path: /Users/giovanni/Desktop/Tesi di Laurea/images

comet:
  api_key: f0ogWRIW8kCHAzBzpvnkh1kbn
  project_name: gait-detection
  workspace: Joyde-1

browse_path: False

save_image:
  plot_prediction: True

show_image:
  plot_prediction: False

train_yolo_pose_model_path: yolo_pose_detection/config/gait_train_yolo_pose_model.yaml

data:
  image_width: 128 # 256
  image_height: 128 # 192
  image_size: 128 # 192# 640
  val_size: 0.25
  test_size: 0.2

training:
  model_name: yolo11n-pose  # yolo11n-pose
  epochs: 1
  batch_size: 32
  device: cpu # cpu mps
  checkpoints_dir: /Users/giovanni/Desktop/Tesi di Laurea/model_checkpoints/gait_yolo_pose_detection
  min_delta: 0
  patience: 90
  start_from_epoch: 16